'use client';

import { useState } from 'react';

import Heading from '../heading';
import Subtitle from '../subtitle';
import Text from '../text';

import './index.scss';

const SessionManagement = () => {
  const [activeTab, setActiveTab] = useState('server');

  const renderTabContent = () => {
    switch (activeTab) {
      case 'server':
        return (
          <div>
            <Subtitle>Server-side Session Management</Subtitle>
            <Text
              size='fs-16'
              color='neutral-700'
            >
              Keeps session data on the server, offering centralized control but requiring more
              server resources for large-scale applications.
            </Text>
            <ul>
              <li>
                Session data is stored on the server side, typically in memory or a storage system
                like a database or cache.
              </li>
              <li>
                Resource-intensive for the server, especially with a large number of concurrent
                sessions.
              </li>
            </ul>
          </div>
        );
      case 'token':
        return (
          <div>
            <Subtitle>Token-based Session Management</Subtitle>
            <Text
              size='fs-16'
              color='neutral-700'
            >
              Utilizes tokens like JWT for secure and scalable user authentication without relying
              on server-side storage.
            </Text>
            <ul>
              <li>
                Uses secure tokens, such as JSON Web Tokens (JWT) or opaque tokens generated by the
                server.
              </li>
              <li>Enhances security and flexibility when tokens are signed and encrypted.</li>
            </ul>
          </div>
        );
      case 'cookie':
        return (
          <div>
            <Subtitle>Cookie-based Session Management</Subtitle>
            <Text
              size='fs-16'
              color='neutral-700'
            >
              Stores session information in the browser&apos;s cookies, simplifying state management
              but potentially exposing security risks.
            </Text>
            <ul>
              <li>Relies on session cookies, which expire when the browser is closed.</li>
              <li>
                The client’s browser includes the session cookie in request headers to identify the
                user’s session.
              </li>
              <li>
                HIPAAChecker evaluates if session cookies are present in the front-end web
                application.
              </li>
            </ul>
          </div>
        );
      case 'hidden':
        return (
          <div>
            <Subtitle>Session in Hidden Form Fields</Subtitle>
            <Text
              size='fs-16'
              color='neutral-700'
            >
              Embeds session data in HTML form fields, sending it with each form submission but
              making the process less secure and more resource-intensive.
            </Text>
            <ul>
              <li>
                HTML forms store session IDs in hidden form fields, submitting them with each form
                submission.
              </li>
              <li>This method is computationally expensive and insecure.</li>
            </ul>
          </div>
        );
      default:
        return null;
    }
  };

  return (
    <div className='sessionManagement'>
      <Heading
        title='AUTOMATIC LOGOFF (Addressable) - § 164.312(a)(2)(iii)'
        type='h4'
        color='neutral-800'
      />
      <Text
        size='fs-16'
        color='neutral-700'
      >
        Sample session management questions for a software system to consider:
      </Text>
      <ul>
        <li>Do current information systems have an automatic logoff capability?</li>
        <li>Is the automatic logoff feature activated on all workstations with access to ePHI?</li>
      </ul>

      {/* Overview Section */}
      <div className='featureContent--mt-20 featureContent--mb-20'>
        <Heading
          title='HIPAAChecker to validate your session management'
          type='h5'
          color='neutral-800'
        />
        <Text
          size='fs-16'
          color='neutral-700'
        >
          When choosing a session management method, factors such as security requirements,
          scalability needs, compatibility with client technologies, and performance considerations
          should be taken into account.
        </Text>
      </div>

      {/* Tabs Navigation */}
      <div className='tabs'>
        <button
          className={`tab ${activeTab === 'server' ? 'active' : ''}`}
          onClick={() => setActiveTab('server')}
        >
          Server-side Session
        </button>
        <button
          className={`tab ${activeTab === 'token' ? 'active' : ''}`}
          onClick={() => setActiveTab('token')}
        >
          Token-based Session
        </button>
        <button
          className={`tab ${activeTab === 'cookie' ? 'active' : ''}`}
          onClick={() => setActiveTab('cookie')}
        >
          Cookie-based Session
        </button>
        <button
          className={`tab ${activeTab === 'hidden' ? 'active' : ''}`}
          onClick={() => setActiveTab('hidden')}
        >
          Hidden Form Fields
        </button>
      </div>

      {/* Tab Content */}
      <div className='tabContent'>{renderTabContent()}</div>
    </div>
  );
};

export default SessionManagement;
