const API_ENDPOINTS = {
  LOGIN: 'sessions',
  REGISTRATION: 'registrations',
  FORGOT_PASSWORD: 'passwords',
  RESET_PASSWORD: 'passwords',
  UPDATE_PASSWORD: 'passwords/update_password',
  ORGANIZATIONS: 'organizations',
  DASHBOARD: 'dashboard',
  USER_UPLOADS: 'user_uploads',
  GITHUB_URL: 'github_uploads',
  PLANS: 'plans',
  SUBSCRIPTIONS: 'subscriptions',
  USER: 'user',
  USER_UPDATE: (userId) => `user/${userId}`,
  PROMOTIONAL_CODES: 'promotional_codes',
  CANCEL: 'subscriptions/cancel',
  PAYMENT_METHODS: 'payment_methods',
  USER_CONFIRMATION: 'confirmations',
  MEMBERS: 'members',
  CHAT_USER: 'chat/user',
  CHAT_CONVERSATION: 'chat/conversation',
  CHAT_VULNERABILITY: 'chat/vulnerability',
  ROLES: 'roles',
  ADDRESSES: 'addresses',
  INVOICES: 'invoices',
  MANUAL_SELECT: 'manual_selection',
};

export default API_ENDPOINTS;
